### ISSUE TITLE
Download Prescription is not working.

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#601]
Hello @aethelwulffe @teryhill 

When we select `Download PDF` in `Prescription`, then it is giving internal server error. Can you please verify it?

Below is error log.

`PHP Fatal error:  Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /var/www/html/LibreEHR/library/classes/class.pdf.php:2654\nStack trace:\n#0 /var/www/html/LibreEHR/library/classes/class.ezpdf.php(1393): Cpdf->addPngFromFile('/var/www/html/L...', 281, 683.99243243243, '50')\n#1 /var/www/html/LibreEHR/controllers/C_Prescription.class.php(267): Cezpdf->ezImage('/var/www/html/L...', '', '50', '', 'center', '')\n#2 /var/www/html/LibreEHR/controllers/C_Prescription.class.php(607): C_Prescription->multiprint_header(Object(Cezpdf), Object(Prescription))\n#3 /var/www/html/LibreEHR/library/classes/Controller.class.php(146): C_Prescription->multiprint_action('10')\n#4 /var/www/html/LibreEHR/controller.php(6): Controller->act(Array)\n#5 {main}\n  thrown in /var/www/html/LibreEHR/library/classes/class.pdf.php on line 2654, referer: http://localhost/LibreEHR/controller.php?prescription&list&id=3
`

**Comment by aethelwulffe** [comment]
magic quotes stuff hunh...I also thought that expdf was moved to /modules...

**Comment by aethelwulffe** [comment]
@pri2si17-1997 Can you still replicate this?

**Comment by pri2si17-1997** [comment]
@aethelwulffe Yes. I also tried it on https://nhanes.librehealth.io , but there also it is not working. :disappointed:
