### ISSUE TITLE
Setup fails after ACL with Fatal error - missing xml_parser_create()

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#863]
UBUNTU 16.04 LTS Desktop, current master branch.

[Thu Dec 14 15:59:40.228263 2017] [:error] [pid 20440] [client ::1:52718] PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/libreehr-tip/library/adodb/adodb-xmlschema.inc.php:1635\nStack trace:\n#0 /var/www/libreehr-tip/library/adodb/adodb-xmlschema.inc.php(1504): adoSchema->create_parser()\n#1 /var/www/libreehr-tip/library/adodb/adodb-xmlschema.inc.php(1419): adoSchema->ParseSchemaString('<?xml version="...', false)\n#2 /var/www/libreehr-tip/gacl/setup.php(171): adoSchema->ParseSchema('/var/www/libree...')\n#3 /var/www/libreehr-tip/library/classes/Installer.class.php(537): require('/var/www/libree...')\n#4 /var/www/libreehr-tip/library/classes/Installer.class.php(353): Installer->get_require_contents('/var/www/libree...')\n#5 /var/www/libreehr-tip/setup.php(491): Installer->install_gacl()\n#6 {main}\n  thrown in /var/www/libreehr-tip/library/adodb/adodb-xmlschema.inc.php on line 1635, referer: http://localhost/libreehr-tip/setup.php?site=default

![setup-stops-cold](https://user-images.githubusercontent.com/285835/34020362-a707788a-e0e8-11e7-8829-45276e324357.png)

**Comment by tmccormi** [comment]
php XML is not listed as a dependency in the INSTALL.md or other docs.
* sudo apt-get install php7.0-xml (or php-xml)

will update the documentation.
